### ISSUE TITLE
Account Payment - Double Clicking UPDATE button processes 2 payments

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#10]
We've had instances where faulty mice or user error has caused two (or more) account payments to go through incorrectly.  Could the UPDATE button be made to only allow it to be clicked once?  Ie disable it after it's been pressed?

![image](https://cloud.githubusercontent.com/assets/10868496/18746710/e286ccdc-80c0-11e6-81d6-c3c2037d0cf2.png)

**Comment by gazmond** [comment]
I've made the button disable when you click it and re-enabled when it is finished to stop this from happening.

**Comment by barneyday** [comment]
Hasn't worked mate, I just tried it 3 times and it took 3 payments!

![image](https://cloud.githubusercontent.com/assets/10868496/20187593/c1b5429a-a76c-11e6-801d-4ef2b6c5bf6a.png)
