### ISSUE TITLE
Deleting Files does not remove them from the Website

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#100]
Example: WKR571WPS - this had the wrong files stored against it.  We have deleted them as we need them off the site immediately - but the files have not been deleted from the website:

![image](https://user-images.githubusercontent.com/10868496/32659282-eb28694a-c615-11e7-9ab2-be2266a998f0.png)

![image](https://user-images.githubusercontent.com/10868496/32659267-db704b44-c615-11e7-985a-50123f9c635e.png)

**Comment by gazmond** [comment]
My code seems fine. Files are all gone from this product. Do you have another example?  Need to check if the file is still in the rp website table once deleted to work out if it's an rp2 or website problem.

**Comment by barneyday** [comment]
Happy to consider this resolved; will re-open if we see any other issues.
