### ISSUE TITLE
Rep Code Missing when creating Purchase Order from Shopping List (KM)

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#103]
When you create a purchase order manually, it automatically puts the user's rep code into the PO.

However when you create it from the Replenishment > Shopping List Review screen, see below, (clicking Create P/Orders), it doesn't enter the rep code of the user.  Instead it puts the rep code as SHOPLIST (see bottom screen shot).

This can be changed but it's a pain and nobody bothers changing it, which makes tracing it difficult.

![image](https://user-images.githubusercontent.com/10868496/34298793-67eb333c-e717-11e7-9151-e61105115c5c.png)

![image](https://user-images.githubusercontent.com/10868496/34298801-70879030-e717-11e7-9949-0ad60cba595c.png)

**Comment by gazmond** [comment]
See if it works now.

**Comment by barneyday** [comment]
Yes works perfectly.  Thank you :) 👍
