### ISSUE TITLE
URGENT: Adding a SWAP item to shopping basket doesn't add it to the basket!!

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#104]
Sale ref 2048076.

Line 5 is a SWAP.  We've tried adding it to the Shopping Basket by clicking the Lorry, then choosing Delivery from 14 and choosing the shopping basket.  It goes through the motions but the item isn't in the shopping basket and the sale doesn't show anything about it being added:

![image](https://user-images.githubusercontent.com/10868496/34434452-2201ddb4-ec7e-11e7-94c1-53a4d89f348c.png)

![image](https://user-images.githubusercontent.com/10868496/34434456-255df04c-ec7e-11e7-90ec-f42c42ed58fb.png)

**Comment by gazmond** [comment]
It should work now on this order and should be sorted going forward.
