### ISSUE TITLE
Urgent - Service Jobs Vanishing

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#115]
We've had numerous service jobs Vanish lately - and have always put it down to user error, but today we've had one with no explanation so it's time to log it.  If we don't pick up on these, the customers get let down as an engineer doesn't turn up at all or they go to a wrong house.

Please see attached job sheet - this job was booked at 09:10 this morning (19/02/2018).

![image](https://user-images.githubusercontent.com/10868496/36374041-ef885ff4-1561-11e8-80b1-0452869b62b4.png)

Now, load that job up in RPii, and it's a totally different job and customer.  It's a job for COLLINGS which was booked in at 08:20 this morning.

The one that Steve booked in at around 09:10 this morning was there, it was in the diary - and as you can see, there's even a job sheet for it.  But now that job sheet has totally vanished from existence.  So - this one was identified because they noticed in the note after they looked at it, a delivery note that said "9am ring first on mobile 07961023773. mark collings".  Well, that wasn't linked to customer "TAYLOR", that note was linked to customer COLLINGS.  So they asked their manager, he said "Print me a copy of the job sheet and I'll check it out."  Steve went into the job, loaded it into POS, clicked Print > Job Sheet, and that's how we got a copy of it.  When Mike (the manager) went to take a look, it had completely vanished and nobody knows anything about deleting it.

Both jobs should be there, note that there's now a new job on the system for TAYLOR which is 99047194 - I asked them to rebook the job cuz otherwise they wouldn't get an engineer turn up.

**Comment by gazmond** [comment]
The job was booked in the test company insitead of live. Maybe we need to disable test company use for general users - restrict access or some such.
