### ISSUE TITLE
Add Warranties Sold to Leaderboards

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#118]
With our increased efforts to push warranty sales, the managers have asked whether the Warranties Sold could be added to the Leaderboards charts.

We would like it to be added to the Shop Reports screen, and have tabs for Today's Warranties and This Month's Warranties.

Under Summary, it just needs to show the Rep Code and total number of warranties sold (by branch, like the sales).

Under Detail, it needs to show the date, sale ref and the warranty type and price (same format as the sales report).

![image](https://user-images.githubusercontent.com/10868496/36529157-61f67ec8-17af-11e8-82e0-dd4a649b5563.png)

**Comment by gazmond** [comment]
Changing date in delivery system now adds audit entry
