### ISSUE TITLE
Can 40 and 90's email addresses please be merged into 44 now?

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#119]
Each month we run a report.  40 and 90 became 44 - so each month we have to run it for all 3 locations and add them together.  Can we please merge the email addresses for 40 and 90 into location 44 so we only need to run it for 44?  Attached is an export of 40 and 90.

[40 + 90 Emails.zip](https://github.com/HBHWoolacotts/RPii/files/1747325/40.90.Emails.zip)

**Comment by barneyday** [comment]
Report is SPCL:CUS1

:![image](https://user-images.githubusercontent.com/10868496/36537689-dd004aa4-17c8-11e8-8875-e8f19e0f1120.png)

**Comment by gazmond** [comment]
Can you test this for me now please?
