### ISSUE TITLE
Paul Gregory: Electrolux Barcode Issues with Examples

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#122]
Here's the barcode:

![image](https://user-images.githubusercontent.com/10868496/37085325-a90b49aa-21ec-11e8-9f6c-16256582c9f3.png)

Here's how it scans on the screen:

![image](https://user-images.githubusercontent.com/10868496/37085351-bb88670c-21ec-11e8-9aa5-729c9b8bf14a.png)

Here's how it scans on his Phone (he can't find the Scan Wedge app on the tablet):

![image](https://user-images.githubusercontent.com/10868496/37088569-b39d8366-21f5-11e8-9516-a6a9774562e7.png)

^^ ALTHOUGH HE SAYS THE SQUARES AREN'T APPEARING ON HIS PHONE.  They appear when he emails it to me (which may give a clue?)

**Comment by barneyday** [comment]
Second Example (with brackets):

![image](https://user-images.githubusercontent.com/10868496/37088591-c7bb9504-21f5-11e8-977b-3fd037412026.png)

Scans at this:

![image](https://user-images.githubusercontent.com/10868496/37088738-49bb0364-21f6-11e8-9801-de8cf6515a8f.png)

Phone recognises it as this:

![image](https://user-images.githubusercontent.com/10868496/37088770-5bd00996-21f6-11e8-8c7f-7d999683cedb.png)

Scanned into Serial Field:

![image](https://user-images.githubusercontent.com/10868496/37089173-9762a24c-21f7-11e8-92fb-0752171511d3.png)

**Comment by gazmond** [comment]
Link for Carl. Page 99.
https://aidc.honeywell.com/CatalogDocuments/D9700%20Software/Naurtech%20CETerm%20Users%20Manual.pdf

**Comment by ghost** [comment]
Barney / Paul.
Go into Naurtech, Session, Configure, Select Symbology Tab.
![image](https://user-images.githubusercontent.com/37143591/37094761-d77a7396-220b-11e8-8de1-5690624ade7b.png)
It shows a list of types of Barcodes (Code 39, Code 93 etc) do you have one for **DataBar** and is it set to Enabled.

**Comment by ghost** [comment]
Can you see if you get an option for Report CHK. (**_Report Check: Check this box to report (or return) the check digit as part of the barcode data_**) next to the UPC-A barcode. See if ticking that - returns the full scan of the barcode.

**Comment by ghost** [comment]
Update: Spoke to @barneyday they are going to send their Palm they are getting back so we can test things here, speak to Naurtech see if they suggest anything.

**Comment by barneyday** [comment]
Honeywell scanner being sent tomorrow (Tues 12th June).

Another live example:

![image](https://user-images.githubusercontent.com/10868496/41244412-dd892cc8-6d9c-11e8-9885-27dd74ac29d1.png)

Scans as 240925070764 (nothing after is there).

**Comment by barneyday** [comment]
Confirmed with Paul Gregory that the only digits that should show are the last block - the serial number - 71730012, so the last 8 digits.  The barcode filters in RPii working should fix this.

**Comment by ghost** [comment]
Right. I'll speak to @gazmond see what can be done.

**Comment by barneyday** [comment]
@gazmond requested an example of Hoover serial (number with no barcode) for new app.

![image](https://user-images.githubusercontent.com/10868496/43000631-26d43a1c-8c1a-11e8-9a71-7ba5765e9cba.png)

**Comment by barneyday** [comment]
Cannot be fixed.  New app to be created by Steve/Gaz - new issue #140
