### ISSUE TITLE
URGENT: Changing Engineer in Service Job - Doesn't Update the Engineer Correctly

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#124]
Example Job: 99047799

![image](https://user-images.githubusercontent.com/10868496/37104583-ffc6a78e-2224-11e8-9e07-82fce2a018ef.png)

As you can see, this was rescheduled at SHOP access level by opening Kevin Lane's Diary, clicking on the job, and clicking the Lorry to reschedule it:

![image](https://user-images.githubusercontent.com/10868496/37104618-147af450-2225-11e8-920e-e9afdd5f701a.png)

They then rescheduled it and picked RK Roland Kelly as the engineer.

The job successfully updated.  It's showing in RK's diary.  HOWEVER, it did NOT print when Roland printed his jobs for the day.  This is the bug.

That's because the Engineer still shows as Kevin Lane KL:

![image](https://user-images.githubusercontent.com/10868496/37104726-59773eb0-2225-11e8-8595-2adcf4d628cd.png)

![image](https://user-images.githubusercontent.com/10868496/37104751-664993a4-2225-11e8-9233-88f8fcf15ceb.png)

**Comment by gazmond** [comment]
Tested and rescheduling through that screen definitely does change the engineer to the correct one, as long as the delivery team is type service and is mapped to an engineer (which RK is). Problem must lie elsewhere - possible that someone reschedules while the job is open somewhere and then it is saved with the old engineer.

**Comment by barneyday** [comment]
No longer an issue it seems so closing issue.
