### ISSUE TITLE
Stock Missing from "Delivery Customer" Record

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#142]
Customer: DURN1959 has 2 addresses (invoice: Windsor Castle, delivery: Raglan Cottages).

If you search in customer tab for DURNFORD >  RAGLAN, the Delivery address appears.

When you open it, there are no sales items there.

If you search in customer tab for DURNFORD > WINDSOR, and open the customer record, the purchased items are there.  (And yes, they were delivered to Ragland Cottages).

Searching Delivery Record:

![image](https://user-images.githubusercontent.com/10868496/43404994-c15bdd1c-9410-11e8-8800-980e3ac23dfb.png)

Searching Invoice Record:

![image](https://user-images.githubusercontent.com/10868496/43405004-c939f2bc-9410-11e8-9b9a-1e17c9ff1ede.png)

**Comment by gazmond** [comment]
I'm not sure how to handle this. The sale was for DURN1959, DURN1958 doesn't feature - a delivery address has been added to that sale. I guess I will have to make the search work on delivery addresses.

![image](https://user-images.githubusercontent.com/20443019/43457931-238fa766-94c0-11e8-82dc-98b65d89d9d4.png)

**Comment by barneyday** [comment]
Migrated to GL:
https://gitlab.com/barney.day/HBHWoolacotts/issues/13
