### ISSUE TITLE
Account > Make Payment - if you select INVOICE, it clears the balance!

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#143]
Any sale with an outstanding balance - if you go customer account > make payment, and choose method INVOICE, it clears the balance.  Ideally INVOICE shouldn't show (cash, cheque and card should be the only options that show at shop level), or if it does show, it shouldn't clear the balance.

**Comment by gazmond** [comment]
Invoie payment type is set with access level of 5. I've made account payments honour the unpaid flag
