### ISSUE TITLE
Small Mod to RETRA Warranty Report

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#157]
Hi Gaz

RETRA are insisiting we populate columns O and P for them (we do this manually but it would save time if the report pre-populated it).

Column O (product_type) needs to be populated with Television for every line.
Column P (manufacturer)  needs to be filled with Samsung.

Also - can we please remove comumns A (group) and B (brand) from the report and shift everything over by 2 columns?  As A and B are not used and we have to manually delete them.

Please can this be done before the next report.

Many thanks.

**Comment by gazmond** [comment]
Ive done this and sent a copy. Please confirm it is OK.

**Comment by barneyday** [comment]
Perfect, thanks :)
