### ISSUE TITLE
Shops (lower access) need to be able to enter more info after a job is booked 

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#16]
Some of the fields need to be editable - usually because a customer 'comes back' or 'phones in' with the missing information; or it's keyed incorrectly. 

This presumably ONLY applies to jobs where the item was NOT purchased from us and they have to load the item manually when booking the job.

Ability to edit:

- Model Number
- Stock Number
- Serial Number(s)

**Comment by gazmond** [comment]
Chargeable dev, approx 2 hours

**Comment by gazmond** [comment]
![image](https://cloud.githubusercontent.com/assets/20443019/22692338/635ca502-ed36-11e6-8636-ae5e387ac433.png)
![image](https://cloud.githubusercontent.com/assets/20443019/22692347/6f4bdd9c-ed36-11e6-9a06-068bc977bb7f.png)
