### ISSUE TITLE
Stock Number shows as 'Reserved' when it should be Sold

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#18]
Sale ref 1899643, line 2, stock number 1225068.

Item shows as Delivered but stock number shows Reserved.  Serial hasn't updated on delivery completion.

![image](https://cloud.githubusercontent.com/assets/10868496/20351247/f8750c06-ac09-11e6-89f4-26b0a2f57036.png)

**Comment by gazmond** [comment]
I can't reproduce this and, as it happened back at the beginning of october, I no longer have the log files to try and work out what happened. I did go through the code and compare to data but it all looks fine. I have fixed the stock number, keep an eye open for any others.
