### ISSUE TITLE
Changing "Charge Type" Issues

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#2]
When they change a charge type from Standard Chargeable to Warranty, the job sheet does not update - so the engineers do not see this change.
Also the charge customer doesn't change.  This is usually only ever a problem when the system does not detect an item under warranty.  Therefore it's usually only ever changed from Chargeable to Warranty or Extended Warranty.  The issue is that if you change it to Warranty, when the job is complete and invoiced, the Customer still gets the invoice because the customers aren't being updated.  It's causing a big problem because the customer then gets a bill and the manufacturer doesn't - Maggie has to go in and change each one manually in POS.

![image](https://cloud.githubusercontent.com/assets/10868496/18584342/0712a6c4-7c08-11e6-9c7a-2dd51ce2f755.png)

**Comment by barneyday** [comment]
Hi @gazmond 

The problem here is that the Charge info isn't updated.  So for example, here are two jobs that have been modified:

99025669 Was Normal charge to customer, now changed to Warranty Charge - but invoice customer still shows as chargeable to customer.

99025643 Was Warranty charge - now Normal Chargeable - but invoice customer still shows as chargeable to Warranty (Sony).

The problem is when the job gets finished and invoiced, a customer will get the bill when it's supposed to be warranty, and vice versa.

**Comment by gazmond** [comment]
Needs testing on f9

**Comment by barneyday** [comment]
Doesn't work matey.

Two examples just tested:

99023052 Normal charge > warr charge - should be invoiced to warranty provider but not

99024940 Warranty charge > Norm charge - should be invoiced now to customer but not

**Comment by gazmond** [comment]
can you test on f9 now?

**Comment by barneyday** [comment]
Job 99030976 - job was modified from Chargeable to Under Warranty - the job has updated and shows Warranty but the charge info still shows the customer which is wrong.

![image](https://cloud.githubusercontent.com/assets/10868496/22931806/ee83721e-f2bd-11e6-86e5-ca407b0ac60d.png)

**Comment by barneyday** [comment]
@gazmond has removed the 'charge to' info from the Job Edit screen, update to follow and testing to continue.  I'll close this issue and will open a new one if we experience any further problems.
