### ISSUE TITLE
Panasonic Store Web Orders come through using Panasonic Model No not HBH Model

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#21]
Sale ref 1924083 - line 1 is a TX-50DX750B.  Our model is TX50DX750B.

I've fixed this one now but it never used to do this.

![image](https://cloud.githubusercontent.com/assets/10868496/20439817/4fd592b6-adb5-11e6-8b67-db1fe989c51c.png)

**Comment by gazmond** [comment]
It relies on the correct Manufacturer part number being on the system. In this case, the MPN is incorrect against the product so our system has no way of being able to cross-referencing it.

![image](https://cloud.githubusercontent.com/assets/20443019/20600478/c1b5cea6-b24b-11e6-9430-11189f8d16d2.png)
