### ISSUE TITLE
Sale suddenly appearing on Loan/Appro Report (not there last week)

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#22]
Please see two reports sent by email:

Loan/Appro ref 1828329:
LOANDET - 11-11-2016.csv - loan/appro does not exist
LOANDET - 21-11-2016.csv - loan/appro exists on Line 37

The loan/appro was modified recently which is why it has appeared (I think?) but why was it not on last week's loan/appro report?  Worried we are missing many others?

**Comment by gazmond** [comment]
When this sale was originally put on the system, the user did not convert it to a loan. It looks like they just closed the browser. It wasn't converted to a loan until 12/11/16
