### ISSUE TITLE
Auto Rent serial numbers - I've found where they come from!

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#25]
Someone has cancelled a rental agreement (30035). 
They did NOT return the stock (Rental > Actions > Return Selected Items).

I've just done it [returned it to stock].  And when I did it, the stock stayed attached to the rental sale. But it also created an Auto Rental. 

Stock number is 1112553 - you'll see 2 entries for this now!  This has been a massive problem for ages but never seen exactly where it's happening.

![image](https://cloud.githubusercontent.com/assets/10868496/20572264/b220b32e-b1a2-11e6-9dec-723cbe02b579.png)

**Comment by gazmond** [comment]
Fixed. Please test and confirm.

**Comment by barneyday** [comment]
Working well, thanks :-)
