### ISSUE TITLE
Cancelled Approval vanishes from Customer's Tab - even with outstanding balance

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#27]
This approval disappeared from the customer's tab after it was cancelled.  It's caused a problem because it had a £439.99 credit on it that needed refunding but they couldn't find it!

Ref 1924193 [has since been refunded]

If any sale - invoiced or uninvoiced - has a balance or credit, please can you make sure it stays visible in the customer's tab?

Even now, it does not show in the Customer tab.

![image](https://cloud.githubusercontent.com/assets/10868496/20606131/f19970c6-b266-11e6-82a3-e70594547024.png)

**Comment by gazmond** [comment]
They will now show if there is a balance.
