### ISSUE TITLE
Editable Fields for Engineers Required

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#3]
Engineers cannot edit the following fields and need to be able to do so:

Product (allowing them to modify a make/model/serial/date of purchase)
Fault (allowing them to modify a fault description or add more info)

**Comment by barneyday** [comment]
Sorry @gazmond - can we please also have the ability to modify the Date of Purchase?  As this currently often isn't entered when booking the job and the engineers like to add it in so the details are all up to date.

**Comment by gazmond** [comment]
![image](https://cloud.githubusercontent.com/assets/20443019/18741334/836c9584-80a6-11e6-8652-36cfde66d595.png)

![image](https://cloud.githubusercontent.com/assets/20443019/18741341/95dfb728-80a6-11e6-8083-3eccdf825880.png)
