### ISSUE TITLE
Email Invoice Balance is incorrect if an item is returned from the sale

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#35]
Example sale ref, 1926949 - email invoice sent, showing total balance of £1709.99; PDF attachment is correct at £1639.99 (£70 TVB-CL1000 Returned).

See screen shots:

![image](https://cloud.githubusercontent.com/assets/10868496/21100773/c0bff4d8-c06d-11e6-9993-a9a5c086f635.png)

![image](https://cloud.githubusercontent.com/assets/10868496/21100765/bb067eea-c06d-11e6-87d0-8d352003365b.png)

**Comment by gazmond** [comment]
This is correct. The sale was invoiced with a value of 1709.99 so, legally, that's what a printed invoice should show. The -£70 will be shown on credit 1934045.

**Comment by barneyday** [comment]
Fair enough, thanks!
