### ISSUE TITLE
When doing a SWAP, if you add item to shopping list, it does not add

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#44]
Example sale ref: 1923016

Line 3 was swapped.  The option is swap NOW or LATER, they clicked LATER.  The delivery screen comes up (as per normal) and added a new item to the shopping list to order one.  The item never appeared in the shopping list and did not get ordered.

![image](https://cloud.githubusercontent.com/assets/10868496/22209241/a733e43a-e17d-11e6-981c-7fd3fcbab1a5.png)

**Comment by gazmond** [comment]
Just tested here. When you do a swap, it never comes up and asks you for location or shopping list or anything, it takes you straight into van delivery. I assume they did a serial swap rather than model swap?

**Comment by barneyday** [comment]
Yes that's correct - a serial swap (model swaps can only be carried out at access level 99). That screen you mention is where they add it to the shopping list:

![image](https://cloud.githubusercontent.com/assets/10868496/22684805/cefbaf86-ed15-11e6-98de-6f2f8dbe45ef.png)
