### ISSUE TITLE
Manifest Issue - "Picked" Serial Numbers are showing on the Available list again

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#47]
This happend a few months back but has just recently started happening again.

Numbers that have already been picked are showing in the Available Serials list.

![image](https://cloud.githubusercontent.com/assets/10868496/22585775/650b4720-e9f1-11e6-9df5-19a68e54c146.png)

**Comment by gazmond** [comment]
Struggling to reproduce this issue :/

**Comment by gazmond** [comment]
I kinda thought this was fixed with the last upodate. Let me know if it is still occuring.

**Comment by barneyday** [comment]
February!  I think it's been fixed as it's not been mentioned since.  Let's say we're happy with it until someone else mentions it.
