### ISSUE TITLE
Add-on items being removed still show in the sale balance

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#52]
EXAMPLE SALE: 1958754

Addon item was removed but you can see the value of £99.99 is still included in the sale balance.

[nb this sale can be deleted once problem is fixed, as it's now loaded correctly on a different sale on the customer's account]

![image](https://cloud.githubusercontent.com/assets/10868496/22983641/9fe61b10-f39a-11e6-93b3-d6d33abecbd1.png)

**Comment by gazmond** [comment]
Think I've fixed this now. can you test on f9?

**Comment by barneyday** [comment]
Haven't tested it on F9 but it works on live!
