### ISSUE TITLE
Wrong Price Tickets being shown for Re-Print

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#56]
We have several examples of price tickets which have had their prices changed, but aren't coming up on the "new" ticket system.

This model is an example - DXC510W3.  Using the following criteria under Search:

![image](https://cloud.githubusercontent.com/assets/10868496/23134118/875a071a-f78b-11e6-8530-0e0f97c09547.png)
![image](https://cloud.githubusercontent.com/assets/10868496/23134138/99ae71f8-f78b-11e6-8065-baf716fbf79e.png)

The following model should appear, but doesn't (this had a price set to change on this date):

![image](https://cloud.githubusercontent.com/assets/10868496/23134164/b411a34e-f78b-11e6-8cfc-6123746dd2a4.png)

Another example is model DXC4C47B1; changed 15/02/2017.

**Comment by gazmond** [comment]
See if that's any better
