### ISSUE TITLE
Feature Request - can we the ability to store a repetative Note into the Delivery Team Diary?

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#57]
Notes like these get entered in daily (which is a pain!).

It would be a great feature if we could save notes on a repetative basis so they always show.

Required for Manager Access Level (55) and above only - if it's easier though, something under the System tab could be used?

![image](https://cloud.githubusercontent.com/assets/10868496/23134939/9050c202-f78e-11e6-9999-b04c252f6e75.png)

**Comment by gazmond** [comment]
![image](https://cloud.githubusercontent.com/assets/20443019/23260719/11c1396e-f9cb-11e6-8c76-f835954b5798.png)

**Comment by barneyday** [comment]
Fantastic, thank you!

**Comment by barneyday** [comment]
@gazmond is it possible to add something into value 2 or value 3 to only show this note on certain days?  eg, Mon and it'll only show it Mondays?
