### ISSUE TITLE
Add-on Item Prices are changing to 9999999.00 when you add a quantity [3 issues]

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#58]
I'm not sure why the ADD QUANTITY button is there actually because they are usually only entitled to 1 child item with a parent product, adding another seems like a bit of a potential way to cheat the system?

Anyway - to reproduce it, do the following:

- Sell model TX50DX750B on a new sale
- Apply the add-on "SCHTB485BK"
- Click the "Add Quantity" button on the add-on line
- The price will change to 999999.00 and the whole sale

![image](https://cloud.githubusercontent.com/assets/10868496/23220387/c59851aa-f919-11e6-9710-547b42ee210e.png)

ADDITIONALLY, if you then remove the child items and the parent item, the balance of the addon stays on the sale:

![image](https://cloud.githubusercontent.com/assets/10868496/23220501/238fe7f0-f91a-11e6-9057-e5073da06bee.png)

ADDITIONALLY ADDITIONALLY: If you then try to add the parent item again and try to pick the add-on manually, it won't allow you to choose the add-on!

**Comment by barneyday** [comment]
Linked to issue #52

**Comment by gazmond** [comment]
The button shouldn't have been there at all. I've removed it now.
