### ISSUE TITLE
If SWAP is carried out and item is added to Basket, it says it's been added but does not add it

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#66]
Sale ref 1948534

A swap was carried out - when you look at the audit it says **Line 3 added to shopping basket**, but the item was not added in and did not get ordered.

They can get around it by creating an Appro and adding that but it's not ideal as it will often get forgotten.

![image](https://cloud.githubusercontent.com/assets/10868496/24190979/29b99454-0ee2-11e7-9edb-e5dbe0623496.png)

**Comment by gazmond** [comment]
I just tested this on dev. I'll update f9 so you can test it there
