### ISSUE TITLE
Outstanding Deliveries items being deleted - add to sale audit

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#79]
We had a situation where Bude requested a TV from Bodmin, sale ref 1987583.
Bodmin realised that they were supposed to have reserved that TV for a customer and deleted the stock request, but forgot to ring Bude.  The set never got sent and we were unsure as to who deleted it.  This does happen from time to time.

It would be really useful if there's outstanding deliveries for stock requests for a sale, and they get deleted, if the sale audit could show that it was deleted and who by.  This would make fault finding with our staff/internal system a lot easier.

**Comment by gazmond** [comment]
Fixed. Please test.
