### ISSUE TITLE
Please remove redundant Web options from MyList

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#81]
Set Web Category 1
Set Web Category 2

These are no longer required as we use "Set New Web Category" not the old categories and it causes confusion.

Also we tried "Remove from Category ID" to remove a category but this did not work. What is this for?  We then tried "Remove ALL Category Assignments" but it was a bit ambiguous as to what that would do.  Could that perhaps say "Remove Web Categories"? 

![image](https://cloud.githubusercontent.com/assets/10868496/26819228/de5c879c-4a95-11e7-8242-5ec175a78741.png)

**Comment by gazmond** [comment]
These are no longer required by you but other people need them in there.
