### ISSUE TITLE
Martin: Issue with End of Day Report & Web Sales

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#9]
I think there is an issue with the Web Sales reporting on RP.
It used to work that any sales that arrived before the EOD report at 7pm arrived on that days sales, any after that time were counted as the next day. 
This now appears to have changed – please see below a screenshot of yesterday’s sales run from RP this morning and attached the 7pm EOD report, as you can see the sales that arrived between 7pm and midnight show on yesterday’s sales but not the EOD report. They should be showing on todays sales.
I’m concerned that these sales will get missed.

![image](https://cloud.githubusercontent.com/assets/10868496/18670661/e814ea28-7f38-11e6-825c-a4632fba5a6c.png)

[YSALESUMDET.txt](https://github.com/HBHWoolacotts/RPii/files/482566/YSALESUMDET.txt)

**Comment by gazmond** [comment]
It was the scheduler running for the new website. I've adjusted the times it runs now so this should work correctly going forward.
