### ISSUE TITLE
Accept/Decline Buttons are HIDDEN in POS for HOME REPAIRS - Please Show Them

### ISSUE THREAD

**Issue by barneyday** [HBHWoolacotts/RPii#94]
This was done by design as Tara originally managed the Home Repairs.

Now that Estimates for these are going to the booking location, we would like the Shops to be able to Accept or Decline the estimates, so please can these buttons be enabled.

Do they send an email and if yes who to please?

**Comment by gazmond** [comment]
Doesn't look like it's sending any emails when the branch does it.

**Comment by barneyday** [comment]
May need an email to go with these but we will try without and see how it goes.
